export const TOP_CREATORS_COUNT = process.env.TOP_CREATORS_COUNT ? parseInt(process.env.TOP_CREATORS_COUNT) : 25;
export const FREEMIUM_TRENDING_CREATORS = process.env.FREEMIUM_TRENDING_CREATORS || '';
export const MOXIE_BACKEND_INTERNAL_URL = process.env.MOXIE_BACKEND_INTERNAL_URL || '';