import { SubjectToken } from "../protocolSubgraph";

export const mockSubjectTokenDetail: SubjectToken = {
    id: "0x123",
    name: "Test Subject Token",
    symbol: "TEST",
    decimals: 18,
    currentPriceInMoxie: "100",
    currentPriceInWeiInMoxie: "100",
    reserve: "100",
    reserveRatio: "100",
    totalSupply: "100",
    initialSupply: "100",
    uniqueHolders: "100",
    lifetimeVolume: "100",
    subjectFee: "100",
    protocolFee: "100",
    buySideVolume: "100",
    sellSideVolume: "100",
    totalStaked: "100",
    protocolTokenInvested: "100",
    marketCap: "100",
    subject: {
        id: "0x123",
    },
    isGraduated: true,
};

export const mockSubjectTokenDetails: Record<string, SubjectToken> = {
    "0x123": mockSubjectTokenDetail,
    "0x456": {
        id: "0x456",
        name: "Test Subject Token 2",
        symbol: "TEST2",
        decimals: 18,
        currentPriceInMoxie: "100",
        currentPriceInWeiInMoxie: "100",
        reserve: "100",
        reserveRatio: "100",
        totalSupply: "100",
        initialSupply: "100",
        uniqueHolders: "100",
        lifetimeVolume: "100",
        subjectFee: "100",
        protocolFee: "100",
        buySideVolume: "100",
        sellSideVolume: "100",
        totalStaked: "100",
        protocolTokenInvested: "100",
        marketCap: "100",
        subject: {
            id: "0x456",
        },
        isGraduated: true,
    },
};
